/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Bruno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usuarioNome = new javax.swing.JLabel();
        usuarioCargo = new javax.swing.JLabel();
        usuarioAcesso = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        usuarioDesconectar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        telaFundo = new javax.swing.JDesktopPane();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        cadHosp = new javax.swing.JMenuItem();
        ConsultaHosp = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        cadQuarto = new javax.swing.JMenuItem();
        ConsultaQuarto = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        cadFunc = new javax.swing.JMenuItem();
        consultaFunc = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        cadForn = new javax.swing.JMenuItem();
        consultaForn = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        cadProd = new javax.swing.JMenuItem();
        consultaProd = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        cadServ = new javax.swing.JMenuItem();
        consultaServ = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadReserva = new javax.swing.JMenuItem();
        consultarReserva = new javax.swing.JMenuItem();
        finalizarReserva = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        prodVendas = new javax.swing.JMenuItem();
        servVendas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        cadContasPagar = new javax.swing.JMenuItem();
        consultaContasPagar = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        cadContasReceber = new javax.swing.JMenuItem();
        consultaContasReceber = new javax.swing.JMenuItem();
        balanco = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        relContasPagar = new javax.swing.JMenuItem();
        relContasReceber = new javax.swing.JMenuItem();
        relBalanco = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        relQuartosDisp = new javax.swing.JMenuItem();
        relQuartosOcup = new javax.swing.JMenuItem();
        relReservasFuturas = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        estoque = new javax.swing.JMenuItem();
        relHospedes = new javax.swing.JMenuItem();
        relFuncionarios = new javax.swing.JMenuItem();
        relFornecedores = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        addImg = new javax.swing.JMenuItem();
        deleteImg = new javax.swing.JMenuItem();
        resetImg = new javax.swing.JMenuItem();
        sistema = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hotel.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel2.setText("MyHotel");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("HORA");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Usuário:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Cargo:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Acesso:");

        usuarioNome.setText("nome");

        usuarioCargo.setText("texto");

        usuarioAcesso.setText("texto");

        jCalendar1.setWeekOfYearVisible(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Check-ins");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Check-outs");

        jCalendar2.setWeekOfYearVisible(false);

        usuarioDesconectar.setText("Desconectar");
        usuarioDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioDesconectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usuarioCargo)
                                            .addComponent(usuarioNome)
                                            .addComponent(usuarioAcesso)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel11)))
                        .addGap(0, 501, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(usuarioDesconectar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usuarioNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(usuarioCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(usuarioAcesso))
                .addGap(28, 28, 28)
                .addComponent(usuarioDesconectar)
                .addGap(21, 21, 21)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Sistema de Hotel - Desenvolvido por Bruno Moreno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(513, 513, 513))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo4.jpg"))); // NOI18N

        telaFundo.setLayer(fundo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaFundoLayout = new javax.swing.GroupLayout(telaFundo);
        telaFundo.setLayout(telaFundoLayout);
        telaFundoLayout.setHorizontalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        telaFundoLayout.setVerticalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastros.png"))); // NOI18N
        jMenu1.setText("Cadastros   |");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/guest.png"))); // NOI18N
        jMenu9.setText("Hóspedes");

        cadHosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        cadHosp.setText("Cadastrar");
        cadHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadHospActionPerformed(evt);
            }
        });
        jMenu9.add(cadHosp);

        ConsultaHosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        ConsultaHosp.setText("Consultar");
        jMenu9.add(ConsultaHosp);

        jMenu1.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quartos.png"))); // NOI18N
        jMenu10.setText("Quartos");

        cadQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        cadQuarto.setText("Cadastrar");
        jMenu10.add(cadQuarto);

        ConsultaQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        ConsultaQuarto.setText("Consultar");
        jMenu10.add(ConsultaQuarto);

        jMenu1.add(jMenu10);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        jMenu8.setText("Funcionários");

        cadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        cadFunc.setText("Cadastrar");
        cadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncActionPerformed(evt);
            }
        });
        jMenu8.add(cadFunc);

        consultaFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        consultaFunc.setText("Consultar");
        jMenu8.add(consultaFunc);

        jMenu1.add(jMenu8);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        jMenu11.setText("Fornecedores");

        cadForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        cadForn.setText("Cadastrar");
        jMenu11.add(cadForn);

        consultaForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        consultaForn.setText("Consultar");
        consultaForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaFornActionPerformed(evt);
            }
        });
        jMenu11.add(consultaForn);

        jMenu1.add(jMenu11);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        jMenu12.setText("Produtos");

        cadProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        cadProd.setText("Cadastrar");
        jMenu12.add(cadProd);

        consultaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        consultaProd.setText("Consultar");
        jMenu12.add(consultaProd);

        jMenu1.add(jMenu12);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/services.png"))); // NOI18N
        jMenu13.setText("Serviços");

        cadServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        cadServ.setText("Cadastrar");
        jMenu13.add(cadServ);

        consultaServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        consultaServ.setText("Consultar");
        jMenu13.add(consultaServ);

        jMenu1.add(jMenu13);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservas.png"))); // NOI18N
        jMenu2.setText("Reservas   |");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cadReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrarReserva.png"))); // NOI18N
        cadReserva.setText("Cadastrar Reserva");
        cadReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadReservaActionPerformed(evt);
            }
        });
        jMenu2.add(cadReserva);

        consultarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultar.png"))); // NOI18N
        consultarReserva.setText("Consultar Reserva");
        jMenu2.add(consultarReserva);

        finalizarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/realizada.png"))); // NOI18N
        finalizarReserva.setText("Finalizar Reserva");
        jMenu2.add(finalizarReserva);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consumo.png"))); // NOI18N
        jMenu3.setText("Vendas   |");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        prodVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        prodVendas.setText("Produtos");
        jMenu3.add(prodVendas);

        servVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/services.png"))); // NOI18N
        servVendas.setText("Serviços");
        jMenu3.add(servVendas);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.png"))); // NOI18N
        jMenu4.setText("Financeiro   |");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contasPagar.png"))); // NOI18N
        jMenu14.setText("Contas a Pagar");

        cadContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        cadContasPagar.setText("Cadastrar");
        jMenu14.add(cadContasPagar);

        consultaContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        consultaContasPagar.setText("Consultar");
        jMenu14.add(consultaContasPagar);

        jMenu4.add(jMenu14);

        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contasReceber2.png"))); // NOI18N
        jMenu15.setText("Contas a Receber");

        cadContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        cadContasReceber.setText("Cadastrar");
        jMenu15.add(cadContasReceber);

        consultaContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        consultaContasReceber.setText("Consultar");
        jMenu15.add(consultaContasReceber);

        jMenu4.add(jMenu15);

        balanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balanco.png"))); // NOI18N
        balanco.setText("Balanço");
        jMenu4.add(balanco);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios.png"))); // NOI18N
        jMenu5.setText("Relatórios   |");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios2.png"))); // NOI18N
        jMenu16.setText("Financeiro");

        relContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contasPagar.png"))); // NOI18N
        relContasPagar.setText("Contas a Pagar");
        relContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relContasPagarActionPerformed(evt);
            }
        });
        jMenu16.add(relContasPagar);

        relContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contasReceber2.png"))); // NOI18N
        relContasReceber.setText("Contas a Receber");
        jMenu16.add(relContasReceber);

        relBalanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balanco.png"))); // NOI18N
        relBalanco.setText("Balanço");
        jMenu16.add(relBalanco);

        jMenu5.add(jMenu16);

        jMenu17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios2.png"))); // NOI18N
        jMenu17.setText("Reservas");

        relQuartosDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/yes2.png"))); // NOI18N
        relQuartosDisp.setText("Quartos Disponíveis");
        relQuartosDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relQuartosDispActionPerformed(evt);
            }
        });
        jMenu17.add(relQuartosDisp);

        relQuartosOcup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/no2.png"))); // NOI18N
        relQuartosOcup.setText("Quartos Ocupados");
        jMenu17.add(relQuartosOcup);

        relReservasFuturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservaFutura.png"))); // NOI18N
        relReservasFuturas.setText("Reservas Futuras");
        jMenu17.add(relReservasFuturas);

        jMenu5.add(jMenu17);

        jMenu18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios2.png"))); // NOI18N
        jMenu18.setText("Vendas");

        estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estoque.png"))); // NOI18N
        estoque.setText("Estoque");
        jMenu18.add(estoque);

        jMenu5.add(jMenu18);

        relHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios3.png"))); // NOI18N
        relHospedes.setText("Hóspedes");
        jMenu5.add(relHospedes);

        relFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios3.png"))); // NOI18N
        relFuncionarios.setText("Funcionários");
        jMenu5.add(relFuncionarios);

        relFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios3.png"))); // NOI18N
        relFornecedores.setText("Fornecedores");
        jMenu5.add(relFornecedores);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seguranca.png"))); // NOI18N
        jMenu6.setText("Segurança   |");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backup3.png"))); // NOI18N
        jMenuItem16.setText("Realizar Backup");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backup.png"))); // NOI18N
        jMenuItem17.setText("Restaurar Backup");
        jMenu6.add(jMenuItem17);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ferramentas.png"))); // NOI18N
        jMenu7.setText("Ferramentas   |");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/images.png"))); // NOI18N
        jMenu19.setText("Tela de Fundo");

        addImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/addImage.png"))); // NOI18N
        addImg.setText("Adicionar Imagem");
        addImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImgActionPerformed(evt);
            }
        });
        jMenu19.add(addImg);

        deleteImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        deleteImg.setText("Excluir Imagem");
        jMenu19.add(deleteImg);

        resetImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reset.png"))); // NOI18N
        resetImg.setText("Resetar");
        jMenu19.add(resetImg);

        jMenu7.add(jMenu19);

        sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema.png"))); // NOI18N
        sistema.setText("Sistema");
        jMenu7.add(sistema);

        jMenuBar1.add(jMenu7);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        sair.setText("Sair");
        sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(telaFundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaFundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadHospActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadHospActionPerformed

    private void cadReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadReservaActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void addImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addImgActionPerformed

    private void consultaFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaFornActionPerformed

    private void relContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relContasPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relContasPagarActionPerformed

    private void relQuartosDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relQuartosDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relQuartosDispActionPerformed

    private void usuarioDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioDesconectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioDesconectarActionPerformed

    private void cadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncActionPerformed
        // TODO add your handling code here:
        TelaCadastroFuncionario tela = new TelaCadastroFuncionario();
        telaFundo.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_cadFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultaHosp;
    private javax.swing.JMenuItem ConsultaQuarto;
    private javax.swing.JMenuItem addImg;
    private javax.swing.JMenuItem balanco;
    private javax.swing.JMenuItem cadContasPagar;
    private javax.swing.JMenuItem cadContasReceber;
    private javax.swing.JMenuItem cadForn;
    private javax.swing.JMenuItem cadFunc;
    private javax.swing.JMenuItem cadHosp;
    private javax.swing.JMenuItem cadProd;
    private javax.swing.JMenuItem cadQuarto;
    private javax.swing.JMenuItem cadReserva;
    private javax.swing.JMenuItem cadServ;
    private javax.swing.JMenuItem consultaContasPagar;
    private javax.swing.JMenuItem consultaContasReceber;
    private javax.swing.JMenuItem consultaForn;
    private javax.swing.JMenuItem consultaFunc;
    private javax.swing.JMenuItem consultaProd;
    private javax.swing.JMenuItem consultaServ;
    private javax.swing.JMenuItem consultarReserva;
    private javax.swing.JMenuItem deleteImg;
    private javax.swing.JMenuItem estoque;
    private javax.swing.JMenuItem finalizarReserva;
    private javax.swing.JLabel fundo;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JMenuItem prodVendas;
    private javax.swing.JMenuItem relBalanco;
    private javax.swing.JMenuItem relContasPagar;
    private javax.swing.JMenuItem relContasReceber;
    private javax.swing.JMenuItem relFornecedores;
    private javax.swing.JMenuItem relFuncionarios;
    private javax.swing.JMenuItem relHospedes;
    private javax.swing.JMenuItem relQuartosDisp;
    private javax.swing.JMenuItem relQuartosOcup;
    private javax.swing.JMenuItem relReservasFuturas;
    private javax.swing.JMenuItem resetImg;
    private javax.swing.JMenu sair;
    private javax.swing.JMenuItem servVendas;
    private javax.swing.JMenuItem sistema;
    private javax.swing.JDesktopPane telaFundo;
    private javax.swing.JLabel usuarioAcesso;
    private javax.swing.JLabel usuarioCargo;
    private javax.swing.JButton usuarioDesconectar;
    private javax.swing.JLabel usuarioNome;
    // End of variables declaration//GEN-END:variables
}
